<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
<!ELEMENT aeropuertos (aeropuerto*)>
<!ELEMENT aeropuerto (nombre, cerrado | abierto)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cerrado (EMPTY)>
<!ELEMENT abierto (EMPTY)>

]>

<aeropuertos>
    <aeropuerto>
        <nombre>Berlín Schönefeld (SFX)</nombre>
        <abierto />
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlín Tempelhof (THF)</nombre>
        <cerrado />
    </aeropuerto>
</aeropuertos>

