<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE documento[
<!ELEMENT documento(cv)>
<!ELEMENT cv (presentacion, (datos_academicos | experiencia_laboral)+, (lectura|deportes|otros)*, referencias*)>
<!ELEMENT presentacion (#PCDATA)>
<!ELEMENT datos_academicos (#PCDATA)>
<!ELEMENT experiencia_laboral (#PCDATA)>
<!ELEMENT lectura (#PCDATA)>
<!ELEMENT deportes (#PCDATA)>
<!ELEMENT otros (#PCDATA)>
<!ELEMENT referencias (#PCDATA)>
]>
<documento>
    <cv>
        <presentacion>Hola, mi nombre es Pepito</presentacion>
        <datos_academicos>Bachillerato en Instituto La Alameda</datos_academicos>
        <experiencia_laboral>Becario en Smokeselling Consulting</experiencia_laboral>
        <experiencia_laboral>Reponedor en Supermercados Manolo</experiencia_laboral>
        <deportes>Alpinismo</deportes>
        <lectura>Tolkien y Realismo mágico</lectura>
        <otros>Aficionado a la fotografía</otros>
    </cv>
</documento>